[theme.light]
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
fontSize = 30

[server]
port = 8501

[browser]
gatherUsageStats = false
